export const taxonomy = [
  {
    // Articles that teach, demonstrate, or guide developers through solving a profile, in tools, or achieving a technical goal
    slug: 'developer-guides',
    name: 'Developer Guides',
    tags: [
      // Tag backend related articles with the following tags
      'backend',
      'Node.js',
      'Express.js',
      'Nest.js',
      'ASP.NET',
      'Python',
      'Django',
      'Ruby',
      'Go',
      'Elixir',
      'PHP',
      'server-side rendering',
      'C Sharp',
      'Laravel',
      // Tag frontend related articles with the following tags
      'frontend',
      'React',
      'Vue.js',
      'Svelte',
      'Solid.js',
      'Next.js',
      'Nuxt',
      'Remix',
      'Inferno.js',
      'Ionic',
      'Angular',
      'JavaScript',
      'Preact',
      'Alpine.js',
      'Qwik',
      'Deno',
      'CSS',
      // Tag database related articles with the following tags
      'MySQL',
      'GraphQL',
      'Postgres',
      'MongoDB',
      'CouchDB',
      'Oracle',
      // Tag mobile related articles with the following tags
      'mobile',
      'Android',
      'iOS',
      'React Native',
      'mobile app development',
      '.NET',
      '.NET Core',
      'Java',
      'Kotlin',
      'Dart',
      'Flutter',
      // Tag deployment related articles with the following tags
      'progressive delivery',
      'blue-green deployment',
      'canary release',
      'dark launch',
      'ring deployment',
      'phased rollout',
      'sustainable software deployment',
      // Tag software best practices related articles with the following tags
      'code hygiene',
      'clean code',
      'naming conventions',
      'best practices',
      'SDLC',
      'testing',
      'automation',
      'Dogfooding',
      'A/B testing',
      'beta testing',
      'technical debt',
      // Tag feature flag related articles with the following tags (avoid broad tags: 'feature management', 'feature flags', 'feature toggles')
      'long lived flags',
      'short lived flags',
      'global feature flags',
      'backend feature flags',
      'frontend feature flags',
      'user targeting',
      'segmentation',
      'kill switches',
      // Tag API related articles with the following tags
      'public management API', 
      'webhook', 
      'segment API',
      // Tag gaming related articles with the following tags
      'gaming',
      'game development',
      'adaptive gaming',
      'Unity',
      'Unreal Engine',
      'GODOT',
      'Phaser',
      'MelonJS',
      'game design',
      'AR',
      'VR',
      // Tag IoT related articles with the following tags
      'IoT',
      'Internet of Things',
      'smart devices',
      'embedded systems',
      'edge computing',
      'firmware',
    ]
  },
  {
    // Articles explaining or announcing ConfigCat SDKs, and integrations with other tools or services
    slug: 'sdks-and-integrations',
    name: 'SDKs & Integrations',
    tags: [
      // Tag SDK related articles with the following tags
      '.NET SDK',
      'Android (Java) SDK',
      'C++ SDK',
      'Dart SDK',
      'Flutter SDK',
      'Elixir SDK',
      'Go SDK',
      'Java SDK',
      'JavaScript SDK',
      'Browser SDK',
      'Bun SDK',
      'Chromium Extension SDK',
      'Cloudflare Worker SDK',
      'Deno SDK',
      'Node.js SDK',
      'React SDK',
      'Vue.js SDK',
      'Kotlin SDK',
      'PHP SDK',
      'Python SDK',
      'Ruby SDK',
      'Rust SDK',
      'Swift SDK',
      'Unity SDK',
      'Unreal Engine SDK',
      // Tag integration related articles with the following tags
      'integration',
      'Amplitude',
      'Bitbucket Pipe',
      'Bitrise Step',
      'CircleCI Orb',
      'DataDog',
      'GitHub Action',
      'Google Analytics',
      'JetBrains/IntelliJ IDE plugin',
      'Jira Cloud Plugin',
      'Mixpanel',
      'monday.com',
      'Slack',
      'Terraform',
      'Trello Power-Up',
      'Segment',
      'Twilio Segment',
      'Visual Studio Code',
      'Zapier',
      'Zoho Flow',
      'OpenFeature',
      'OpenFeature Providers',
    ]
  },
  {
    // Articles about deploying, managing, and scaling applications with modern infrastructure tools and practices
    slug: 'devops-and-infrastructure',
    name: 'DevOps & Infrastructure',
    tags: [
      // Tag DevOps related articles with the following tags
      'DevOps',
      'Docker',
      'Kubernetes',
      'CI/CD',
      'GitOps',
      'CircleCI',
      'Bitrise',
      'Cloud',
      'monitoring',
      'logging',
      'uptime',
      'load balancing',
      'proxy',
      'configuration management',
      'automation',
      'performance optimization',
      'Redis',
      'caching',
      // Tag infrastructure related articles with the following tags
      'infrastructure',
      'Terraform',
      'AWS',
      'serverless',
      'microservices',
      'Infrastructure as Code',
      'containerization',
      'Azure',
    ]
  },
  {
    // Articles covering AI, ML, and automation topics related to software development, DevOps, or ConfigCat
    slug: 'ai-and-machine-learning',
    name: 'AI & Machine Learning',
    tags: [
      // Tag AI related articles with the following tags
      'AI models',
      'ChatGPT',
      'Anthropic',
      'Claude',
      'Gemini',
      'LLMs',
      'GitHub CoPilot',
      'AI Assisted programming',
      'MCP server',
      'Coding Agents',
      // Tag machine learning related articles with the following tags
      'machine learning',
      'Neural Networks',
      'Vector Machines',
      'Stemming',
      'Tokenization',
      'Natural Language Processing',
      'Reinforcement learning',
      'Supervised learning',
    ]
  },
  {
    // Articles on data protection, privacy, and compliance with global standards
    slug: 'security-and-compliance',
    name: 'Security & Compliance',
    tags: [
      // Tag security related articles with the following tags
      'security',
      'DDoS',
      'Hacking',
      'Penetration testing',
      'encryption',
      'SSL',
      'cryptography',
      'Disaster recovery plan',
      'Insurance',
      'Bug bounty',
      'DPA',
      'Data Privacy Agreement',
      'subprocessors',
      'cybersecurity',
      'authentication',
      '2-Factor Authentication',
      'vulnerability',
      'incident',
      // Tag compliance related articles with the following tags
      'compliance',
      'data governance',
      'ISO Compliance',
      'ISO/IEC 27001',
      'privacy',
      'privacy policy',
      'Terms of Service',
      'GDPR',
      'privacy shield',
      'policy',
      'SLA',
    ]
  },
  {
    // Articles about customers, company updates, and developer community stories
    slug: 'stories-and-community',
    name: 'Stories & Community',
    tags: [
      // Tag competitor related articles with the following tags
      'Statsig',
      'LaunchDarkly',
      'Prefab',
      'PostHog',
      // Tag business related articles with the following tags
      'Startup',
      'announcement',
      'business success',
      'growth',
      'high performer',
      'decision maker',
      'e-commerce',
      'pricing',
      'SaaS',
      'reseller',
      // Tag customer related articles with the following tags
      'customer review',
      'customer success story',
      'customer feature request',
      'customer support',
      // Tag collaboration related articles with the following tags
      'collaboration',
      'teams',
      'Slack',
      'Trello',
      'Jira',
      'open source',
      'community',
      // Tag sustainability related articles with the following tags
      'sustainability',
      'environment',
      'environment-friendly',
      'environmental impact',
      'carbon footprint',
      'trees',
      'deforestation',
    ]
  },
];