export const taxonomy = [
    {
      // Articles that teach, demonstrate, or guide developers through solving a profile, in tools, or achieving a technical goal
      slug: 'developer-guides',
      name: 'Developer Guides',
      tags: [
        // Backend related
        'backend',
        'Node.js',
        'Express.js',
        'Nest.js',
        'ASP.NET',
        'Python',
        'Django',
        'Ruby',
        'Go',
        'Elixir',
        'PHP',
        'server-side rendering',
        'C Sharp',
        'Laravel',
        // Frontend related,
        'frontend',
        'React',
        'Vue.js',
        'Svelte',
        'Solid.js',
        'Next.js',
        'Nuxt',
        'Remix',
        'Inferno.js',
        'Ionic',
        'Angular',
        'JavaScript',
        'Preact',
        'Alpine.js',
        'Qwik',
        'Deno',
        'CSS',
        // Database related
        'MySQL',
        'GraphQL',
        'Postgres',
        'MongoDB',
        'CouchDB',
        'Oracle',
        // Mobile related
        'mobile',
        'Android',
        'iOS',
        'React Native',
        'mobile app development',
        '.NET',
        '.NET Core',
        'Java',
        'Kotlin',
        'Dart',
        'Flutter',
        // Deployment related
        'progressive delivery',
        'blue-green deployment',
        'canary release',
        'dark launch',
        'ring deployment',
        'phased rollout',
        'sustainable software deployment',
        // 'software development best practices',
        'code hygiene',
        'clean code',
        'naming conventions',
        'best practices',
        'SDLC',
        'testing',
        'automation',
        'Dogfooding',
        'A/B testing',
        'beta testing',
        'technical debt',
        // Avoid broad tags: 'feature management', 'feature flags', 'feature toggles', 'feature management',
        'long lived flags',
        'short lived flags',
        'global feature flags',
        'backend feature flags',
        'frontend feature flags',
        'user targeting',
        'segmentation',
        'kill switches',
        // API related
        'public management API', 
        'webhook', 
        'segment API',
        // Gaming related
        'gaming',
        'game development',
        'adaptive gaming',
        'Unity',
        'Unreal Engine',
        'GODOT',
        'Phaser',
        'MelonJS',
        'game design',
        'AR',
        'VR',
        // IoT related
        'IoT',
        'Internet of Things',
        'smart devices',
        'embedded systems',
        'edge computing',
        'firmware',
      ]
    },
    {
      // Articles explaining or announcing ConfigCat SDKs, and integrations with other tools or services
      slug: 'sdks-and-integrations',
      name: 'SDKs & Integrations',
      tags: [
        // SDKs related
        '.NET SDK',
        'Android (Java) SDK',
        'C++ SDK',
        'Dart SDK',
        'Flutter SDK',
        'Elixir SDK',
        'Go SDK',
        'Java SDK',
        'JavaScript SDK',
        'Browser SDK',
        'Bun SDK',
        'Chromium Extension SDK',
        'Cloudflare Worker SDK',
        'Deno SDK',
        'Node.js SDK',
        'React SDK',
        'Vue.js SDK',
        'Kotlin SDK',
        'PHP SDK',
        'Python SDK',
        'Ruby SDK',
        'Rust SDK',
        'Swift SDK',
        'Unity SDK',
        'Unreal Engine SDK',
        // Integration related
        'integration',
        'Amplitude',
        'Bitbucket Pipe',
        'Bitrise Step',
        'CircleCI Orb',
        'DataDog',
        'GitHub Action',
        'Google Analytics',
        'JetBrains/IntelliJ IDE plugin',
        'Jira Cloud Plugin',
        'Mixpanel',
        'monday.com',
        'Slack',
        'Terraform',
        'Trello Power-Up',
        'Segment',
        'Twilio Segment',
        'Visual Studio Code',
        'Zapier',
        'Zoho Flow',
        'OpenFeature',
        'OpenFeature Providers',
      ]
    },
    {
      // Articles about deploying, managing, and scaling applications with modern infrastructure tools and practices
      slug: 'devops-and-infrastructure',
      name: 'DevOps & Infrastructure',
      tags: [
        // DevOps related
        'DevOps',
        'Docker',
        'Kubernetes',
        'CI/CD',
        'GitOps',
        'CircleCI',
        'Bitrise',
        'Cloud',
        'monitoring',
        'logging',
        'uptime',
        'load balancing',
        'proxy',
        'configuration management',
        'automation',
        'performance optimization',
        'Redis',
        'caching',
        // Infrastructure related
        'infrastructure',
        'Terraform',
        'AWS',
        'serverless',
        'microservices',
        'Infrastructure as Code',
        'containerization',
        'Azure',
      ]
    },
    {
      // Articles covering AI, ML, and automation topics related to software development, DevOps, or ConfigCat
      slug: 'ai-and-machine-learning',
      name: 'AI & Machine Learning',
      tags: [
        // AI related
        'AI models',
        'ChatGPT',
        'Anthropic',
        'Claude',
        'Gemini',
        'LLMs',
        'GitHub CoPilot',
        'AI Assisted programming',
        'MCP server',
        'Coding Agents',
        // Machine learning related
        'machine learning',
        'Neural Networks',
        'Vector Machines',
        'Stemming',
        'Tokenization',
        'Natural Language Processing',
        'Reinforcement learning',
        'Supervised learning',
      ]
    },
    {
      // Articles about customers, company updates, and developer community stories
      slug: 'stories-and-community',
      name: 'Stories & Community',
      tags: [
        'announcement',
        // Competitors related
        'Statsig',
        'LaunchDarkly',
        'Prefab',
        'PostHog',
        'Startup',
        // Business related
        'business success',
        'growth',
        'high performer',
        'decision maker',
        'e-commerce',
        // Customer related
        'customer review',
        'customer success story',
        'customer feature request',
        'customer support',
        // Pricing related
        'pricing',
        'SaaS',
        'reseller',
        // Collaboration and collaboration tools related
        'collaboration',
        'teams',
        'Slack',
        'Trello',
        'Jira',
        'open source',
        'community',
        // Sustainability relates
        'sustainability',
        'environment',
        'environment-friendly',
        'environmental impact',
        'carbon footprint',
        'trees',
        'deforestation',
      ]
    },
    {
      // Articles on data protection, privacy, and compliance with global standards
      slug: 'security-and-compliance',
      name: 'Security & Compliance',
      tags: [
        // Security related
        'security',
        'DDoS',
        'Hacking',
        'Penetration testing',
        'encryption',
        'SSL',
        'cryptography',
        'Disaster recovery plan',
        'Insurance',
        'Bug bounty',
        'DPA',
        'Data Privacy Agreement',
        'subprocessors',
        'cybersecurity',
        'authentication',
        '2-Factor Authentication',
        'vulnerability',
        'incident',
        // Compliance related
        'compliance',
        'data governance',
        'ISO Compliance',
        'ISO/IEC 27001',
        'privacy',
        'privacy policy',
        'Terms of Service',
        'GDPR',
        'privacy shield',
        'policy',
        'SLA',
      ]
    }
  ];
  